In [1]:
from surprise import Dataset, Reader, SVD, NormalPredictor, accuracy
from surprise.model_selection import cross_validate, train_test_split

# dataset manipulation
import pandas as pd
import numpy as np

In [2]:
# load ratings
dataset_path = "../Transformed_Data/ratings_small.csv"
ratings_df = pd.read_csv(dataset_path)
ratings_df.head()

,UserID,MovieID,Rating
0,1,1193,5
1,1,661,3
2,1,914,3
3,1,3408,4
4,1,2355,5


In [3]:
# A reader is needed and only the rating_scale param is required.
reader = Reader(rating_scale=(1, 5))

In [4]:
ratings = Dataset.load_from_df(ratings_df[["UserID", "MovieID", "Rating"]], reader)

#### 1. First tests on ratings_small ratings dataset

In [5]:
cross_validate(NormalPredictor(), ratings, cv=2)

{'test_rmse': array([1.50723597, 1.50361015]),
 'test_mae': array([1.21169818, 1.20359707]),
 'fit_time': (0.06725645065307617, 0.09212875366210938),
 'test_time': (0.2589411735534668, 0.2641794681549072)}

In [6]:
# Run 5-fold cross-validation and print results
algo =  SVD()
cross_validate(algo, ratings, measures=["RMSE", "MAE"], cv=5, verbose=True)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    0.9280  0.9231  0.9199  0.9264  0.9318  0.9259  0.0041  
MAE (testset)     0.7345  0.7296  0.7284  0.7299  0.7368  0.7319  0.0032  
Fit time          1.10    1.06    1.05    1.06    1.06    1.07    0.02    
Test time         0.12    0.18    0.14    0.18    0.12    0.15    0.03    


{'test_rmse': array([0.92797844, 0.92313612, 0.91989243, 0.92641389, 0.93183034]),
 'test_mae': array([0.73454341, 0.72963469, 0.72837447, 0.72994563, 0.73683885]),
 'fit_time': (1.1020002365112305,
  1.059004545211792,
  1.0535147190093994,
  1.0574216842651367,
  1.0575711727142334),
 'test_time': (0.12447166442871094,
  0.1839587688446045,
  0.14304471015930176,
  0.1768336296081543,
  0.12351536750793457)}

In [38]:
trainset, testset = train_test_split(ratings, test_size=0.25)

# We'll still use the famous SVD algorithm.
algo = SVD()

# Train the algorithm on the trainset, and predict ratings for the testset
algo.fit(trainset)
predictions = algo.test(testset)

# Then compute RMSE
accuracy.rmse(predictions)
accuracy.mae(predictions)

RMSE: 0.9228
MAE:  0.7297


np.float64(0.7296860175145041)

#### 2. Comparison with custom collaborative filtering RS

In [8]:
trainset = ratings.build_full_trainset()

In [9]:
algo.fit(trainset)

In [20]:
uid = str(59)  # raw user id (as in the ratings file). They are **strings**!
iid = str(302)  # raw item id (as in the ratings file). They are **strings**!

# get a prediction for specific users and items.
pred = algo.predict(uid, iid, verbose=True)

user: 59         item: 302        r_ui = None   est = 3.60   {'was_impossible': False}


In [21]:
ratings_df[ratings_df["MovieID"] == 302]

,UserID,MovieID,Rating
1856,18,302,5
7484,53,302,5
8535,59,302,2
22151,166,302,3
30733,216,302,3
50085,343,302,5
73216,518,302,5
92601,648,302,5


In [22]:
display(ratings_df.head())

,UserID,MovieID,Rating
0,1,1193,5
1,1,661,3
2,1,914,3
3,1,3408,4
4,1,2355,5


In [24]:
pred = algo.predict(1, 2355, verbose=True)

user: 1          item: 2355       r_ui = None   est = 4.15   {'was_impossible': False}


In [25]:
# loading custom collaborative prediction
custom_prediction = np.load("../transformed_Data/user_prediction.npy")

In [26]:
# Loading user indices correspondance
user_corres = np.load("../transformed_Data/user_corres_matrix_index.npy")
# Loading movie indices correspondance
movie_corres = np.load("../transformed_Data/movie_corres_matrix_index.npy")
# loading correspondance between movie indices and movie titles
movies_titles = pd.read_csv("../transformed_Data/MovieID_title.csv")

In [27]:
user_corres[0:10]

array([[ 0.,  1.],
       [ 1.,  2.],
       [ 2.,  3.],
       [ 3.,  5.],
       [ 4.,  6.],
       [ 5.,  8.],
       [ 6.,  9.],
       [ 7., 10.],
       [ 8., 11.],
       [ 9., 13.]])

In [28]:
movie_corres[10,1]

np.float64(11.0)

In [29]:
# movie index in matrix user_prediction for movie id = 2355
iid = 2355.
iidx = np.where(movie_corres[:,1] == iid)
iidx

(array([1897]),)

In [30]:
iidx[0][0]

np.int64(1897)

In [31]:
custom_prediction[0, iidx]

array([[3.17793314]])

In [32]:
def get_custom_pred(user_id, movie_id, user_corres = user_corres, movie_corres = movie_corres, custom_pred_mat = custom_prediction):
    
    iidx = np.where(movie_corres[:,1] == movie_id)
    uidx = np.where(user_corres[:,1] == user_id)
    
    return custom_prediction[uidx, iidx][0][0]

In [33]:
get_custom_pred(1, 2355)

np.float64(3.1779331357196807)

In [34]:
for i in range(10):
    print(f"UserID: {ratings_df.loc[i, "UserID"]}, MovieID: {ratings_df.loc[i, "MovieID"]}, true rating: {ratings_df.loc[i, "Rating"]}, custom collaborative prediction: {get_custom_pred(ratings_df.loc[i, "UserID"], ratings_df.loc[i, "MovieID"])} ")


UserID: 1, MovieID: 1193, true rating: 5, custom collaborative prediction: 2.3721876363021344 
UserID: 1, MovieID: 661, true rating: 3, custom collaborative prediction: 3.353747587627718 
UserID: 1, MovieID: 914, true rating: 3, custom collaborative prediction: 3.125727687638634 
UserID: 1, MovieID: 3408, true rating: 4, custom collaborative prediction: 2.487664931796386 
UserID: 1, MovieID: 2355, true rating: 5, custom collaborative prediction: 3.1779331357196807 
UserID: 1, MovieID: 1197, true rating: 3, custom collaborative prediction: 1.9484641328306738 
UserID: 1, MovieID: 1287, true rating: 5, custom collaborative prediction: 2.1788369020556155 
UserID: 1, MovieID: 2804, true rating: 5, custom collaborative prediction: 2.054414136075529 
UserID: 1, MovieID: 594, true rating: 4, custom collaborative prediction: 3.7104443272626746 
UserID: 1, MovieID: 919, true rating: 4, custom collaborative prediction: 2.9936625677493893 


In [35]:
MAE = 0.0
RMSE = 0.0
df_ratio = 0.1
for i in range(int(df_ratio*len(ratings_df))):
    MAE += np.abs(ratings_df.loc[i, "Rating"]-get_custom_pred(ratings_df.loc[i, "UserID"], ratings_df.loc[i, "MovieID"]))
    RMSE += np.square(ratings_df.loc[i, "Rating"]-get_custom_pred(ratings_df.loc[i, "UserID"], ratings_df.loc[i, "MovieID"]))

MAE = MAE/(df_ratio*len(ratings_df))
RMSE = np.sqrt(RMSE/(df_ratio*len(ratings_df)))
print(f"MAE of custom collaborative RS: {MAE}, RMSE of custom collaborative RS: {RMSE}")


MAE of custom collaborative RS: 0.9904207876614743, RMSE of custom collaborative RS: 1.2169334996843901


In [ ]:
for i in range(10):
    print(f"true rating: {ratings_df.loc[i, "Rating"]}") #,  surprise: {algo.predict(ratings_df.loc[i, "UserID"], ratings_df.loc[i, "MovieID"], verbose=True)[0]} ")


true rating: 5
true rating: 3
true rating: 3
true rating: 4
true rating: 5
true rating: 3
true rating: 5
true rating: 5
true rating: 4
true rating: 4


In [36]:
type(algo.predict(ratings_df.loc[i, "UserID"], ratings_df.loc[i, "MovieID"], verbose=True))

user: 69         item: 1682       r_ui = None   est = 4.22   {'was_impossible': False}


surprise.prediction_algorithms.predictions.Prediction